name: Build NBD
on: [push]
jobs:
  Build-NBD:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - run: ./autogen.sh
      - run: ./configure --enable-syslog
      - run: make distcheck
